server:
  port: 9090

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: ${POSTGRES_CONNECTION_POOL:2}

    url: ${POSTGRES_CONNECT_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${POSTGRES_AUTO_DDL:create-drop}
